@extends('layouts.app') @section('title',($investment->exists?'Editar':'Novo').' investimento | Administração') @section('content')
<main class="container py-5"><h1>{{ $investment->exists?'Editar':'Novo' }} investimento</h1><x-admin-nav />
@if($errors->any())<div class="alert alert-danger" role="alert"><strong>Revise os campos.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $investment->exists?route('admin.investimentos.update',$investment):route('admin.investimentos.store') }}">@csrf @if($investment->exists)@method('PUT')@endif
<div class="row g-3"><div class="col-md-8"><label class="form-label" for="name">Nome</label><input class="form-control" id="name" name="name" value="{{ old('name',$investment->name) }}" required></div><div class="col-md-4"><label class="form-label" for="investment_category_id">Categoria</label><select class="form-select" id="investment_category_id" name="investment_category_id">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('investment_category_id',$investment->investment_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div>
@if($investment->exists)<div class="col-12"><label class="form-label" for="slug">Slug</label><input class="form-control" id="slug" name="slug" value="{{ old('slug',$investment->slug) }}"><small>Deixe em branco para preservar o atual.</small></div>@endif
<div class="col-12"><label class="form-label" for="short_description">Resumo</label><textarea class="form-control" id="short_description" name="short_description" required>{{ old('short_description',$investment->short_description) }}</textarea></div>
@foreach(['description'=>'Descrição','risk_description'=>'Risco','liquidity_description'=>'Liquidez','profitability_description'=>'Rentabilidade','taxation_description'=>'Tributação','protection_description'=>'Proteção','advantages'=>'Vantagens','points_of_attention'=>'Pontos de atenção'] as $field=>$label)<div class="col-12"><label class="form-label" for="{{ $field }}">{{ $label }} (Markdown)</label><textarea class="form-control font-monospace" id="{{ $field }}" name="{{ $field }}" rows="5" @if(in_array($field,['description','risk_description','liquidity_description','profitability_description'])) required @endif>{{ old($field,$investment->$field) }}</textarea></div>@endforeach
<div class="col-md-6"><label class="form-label" for="risk_level">Risco</label><select class="form-select" id="risk_level" name="risk_level">@foreach(['low'=>'Baixo','moderate'=>'Moderado','high'=>'Alto','variable'=>'Variável'] as $value=>$label)<option value="{{ $value }}" @selected(old('risk_level',$investment->risk_level)===$value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label" for="sort_order">Ordem</label><input class="form-control" type="number" min="0" id="sort_order" name="sort_order" value="{{ old('sort_order',$investment->sort_order??0) }}" required></div>
<div class="col-12"><fieldset><legend class="h5">Fontes</legend>@foreach($sources as $source)<div class="form-check"><input class="form-check-input" type="checkbox" name="sources[]" value="{{ $source->id }}" id="source-{{ $source->id }}" @checked(in_array($source->id,old('sources',$investment->exists?$investment->sources()->pluck('sources.id')->all():[])))><label class="form-check-label" for="source-{{ $source->id }}">{{ $source->institution }} — {{ $source->title }}</label></div>@endforeach</fieldset></div>
<div class="col-12"><input type="hidden" name="is_published" value="0"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="is_published" name="is_published" value="1" @checked(old('is_published',$investment->is_published))><label class="form-check-label" for="is_published">Publicado (exige ao menos uma fonte)</label></div></div></div><div class="mt-4"><button class="btn btn-primary">Salvar</button> <a class="btn btn-link" href="{{ route('admin.investimentos.index') }}">Cancelar</a></div></form></main>@endsection
